push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/*
    env:
      python_ver: 3.9

- name: get version
  id: version
  uses: notiz-dev/github-action-json-property@release
  with:
    path: 'plugin.json'
    prop_path: 'Version'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install flowlauncher -t ./lib
    zip -r Flow.Launcher.Plugin.DateDiffPy.zip . -x '*.git*'
- name: Publish
  if: success()
  uses: softprops/action-gh-release@v1
  with:
    files: 'Flow.Launcher.Plugin.DateDiffPy.zip'
    tag_name: "v${{steps.version.outputs.prop}}"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
